version: "3.8"

services:

  # API Gateway
  apigateway:
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Gateway sur port 8080 local
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - backend
    depends_on:
      - client
      - entreprise
      - admin

  # REST Client Service
  client:
    build:
      context: ./servicerestclient
      dockerfile: Dockerfile
    ports:
      - "8081:8080"  # port interne reste 8080, externe 8081
    environment:
      - SPRING_APPLICATION_NAME=service-client
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/rest1_database
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=emf123
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      - mysql
    networks:
      - backend

  # REST Entreprise Service
  entreprise:
    build:
      context: ./servicerestentreprise
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - SPRING_APPLICATION_NAME=service-entreprise
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/rest1_database
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=emf123
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      - mysql
    networks:
      - backend

  # REST Admin Service
  admin:
    build:
      context: ./servicerestadmin
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      - SPRING_APPLICATION_NAME=service-admin
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/rest1_database
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=emf123
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      - mysql
    networks:
      - backend

